{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tfs.fullname" . }}
  labels:
    {{- include "tfs.labels" . | nindent 4 }}
  {{- if or .Values.persistence.retain .Values.persistence.annotations }}
  annotations:
    {{- $annotations := deepCopy .Values.persistence.annotations }}
    {{- if .Values.persistence.retain }}
    {{- $_ := set $annotations "helm.sh/resource-policy" "keep" }}
    {{- $_ := set $annotations "argocd.argoproj.io/sync-options" "Prune=false,Delete=false" }}
    {{- end }}
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- if ne .Values.persistence.storageClass nil }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
